# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: calls, action: index }

 
  
# Display a users calls
calls:
  url: /calls
  param: { module: calls, action: index}

# Get the charges for a call to a specified Destination
get_charges:
  url: /calls/charges
  param: { module: calls, action: getCharges }
 
# Display the details of a bill within the bills list
bill_detail:
  url:   /calls/:billid
  param: { module: calls, action: index }
  requirements:
    billid: \d+
    
# Display a users VM
voicemail:
  url: /voicemail
  param: { module: voicemail, action: index}

# Display a users settings 
settings:
  url: /settings
  param: { module: settings, action: index}



# Manage (admin) residents
resident_list:
  url:   /resident/list
  param: {module: resident, action:index, orderby: room}
  
resident_listByRoom:
  url:   /resident/list/byRoom
  param: {module: resident, action:index, orderby: room}

resident_listByName:
  url:   /resident/list/byName
  param: {module: resident, action:index, orderby: name}

resident_listByLastName:
  url:   /resident/list/byLastName
  param: {module: resident, action:index, orderby: name}
  
resident_listByMoveIn:
  url:   /resident/list/byMoveIn
  param: {module: resident, action:index, orderby: move_in}
    
resident_edit:
  url:   /resident/:residentid/edit
  param: {module: resident, action: edit }
  requirements: 
    residentid: \d+
  
resident_edit_plain:
  url:   /resident/:residentid
  param: {module: resident, action: edit }
  requirements: 
    residentid: \d+

# Access the users actions as if you where the user    
resident_calls:
  url:   /resident/:residentid/calls
  param: {module: calls, action: index }
  requirements: 
    residentid: \d+    
  
resident_vm:
  url:   /resident/:residentid/vm
  param: {module: vm, action:index  }
  requirements: 
    residentid: \d+    
    
resident_settings:
  url:   /resident/:residentid/settings
  param: {module: settings, action: index }
  requirements: 
    residentid: \d+    

resident_phone:
  url:   /resident/:residentid/phone
  param: {module: phone, action: edit}
  requirements: 
    residentid: \d+    

    
# CRUD for Phones
phone_editByRoomNo:
  url:   /phone/room/:roomno
  param: {module: phone, action: edit}
  requirements: 
    roomno: \d+      
  
  
# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
