test:
  hekphone:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;dbname=hekphone_test'
      username: nasen
      password: popel

all:
  hekphone:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;dbname=hekphone'
      username: nasen
      password: popel
  hekdb:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;dbname=hekdb_mirror'
      username: nasen
      password: popel
      